
services:
  frontend:
    build:
      context: ./client
    expose:
      - "80"
    networks:
      - app_network
  
  backend:
    build:
      context: ./server
    networks:
      - app_network
  
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types.conf:/etc/nginx/mime.types.conf:ro
      - /etc/letsencrypt/live/ezconnecty.cc-0001/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ezconnecty.cc-0001/privkey.pem:/etc/ssl/private/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network



networks:
  app_network:
    driver: bridge